services:
  - type: web
    name: tripmate-backend
    runtime: docker
    plan: free
    dockerfilePath: ./dockerfile
    region: oregon
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
